
path:
    #    fastq: '/home/m.mendeville/MPS-408/WES/fastq'
    fastq: 'fastq'
    variant: 'variant'
    copywriter: 'copywriter'
    qc: 'qc'
    bam: 'bam'
    log: 'log'
    covariance: 'CovMetrics'
    temp: 'temp'
    sampleList: 'SamplesTable.tsv'

platform:
    SRorPE: 'PE'
    prefix: ['_R1_001', '_R2_001']

cutadapt:
    adapter: ["AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC", #standard Illumena 
              "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"]

all:
    REF: /net/nfs/PAT/archive/Yongsoo/Resource/fasta/hg19.chr.fa
    THREADS: 18 
    Java_mem: -Xmx4g
    targets: /net/nfs/PAT/archive/Yongsoo/Resource/KAPA_New_Exome/KAPA_HyperExome_hg19_primary_targets.bed
    bait_intervals: /net/nfs/PAT/archive/Yongsoo/Resource/KAPA_New_Exome/KAPA_New_Exome_bait_intervals_HG19_reordered.txt
    target_intervals: /net/nfs/PAT/archive/Yongsoo/Resource//KAPA_New_Exome/KAPA_New_Exome_target_intervals_HG19_reordered.txt
    dbsnp: /net/nfs/PAT/archive/Resource/dbSNP/b151/All_20180423.vcf.gz
    clinvar: /net/nfs/PAT/archive/Resource/dbSNP/b151/clinvar_20180701.vcf.gz
    Cosmic: /net/beegfs/cfg/tgac/Resource/data/ref/cosmic/hg19_v84_2018/CosmicCodingMuts.vcf
    gnomAD: /net/nfs/PAT/archive/Resource/dbSNP/2.0.2/retagged_gnomad.exomes.r2.0.2-AF.vcf.gz
    HMF_PON: /net/nfs/PAT/archive/Resource/data/blacklist/HMF_PON/PON.vcf.gz
    HG19_DICT: /net/nfs/PAT/archive/Resource/fasta/hg19.chr.dict



trim:
    min_len: 20


LoFreq:
    min_cov: 10
    min_mq: 20
    min_bq: 20
    min_alt_bq: 20
    max_depth: 1000
    sig: 0.05
    af_min: 0.05
    cov_min: 15
    sb_alpha: 0.05
    #SnpSift_filter: "(DP4[2]>2) & (DP4[3]>2) & ((na HRUN) | (HRUN<8))"
    BED_blacklist: manifests/PON_LoFreq_N24_min2POS_V2_ABRA2_200430.bed
    #Gene_blacklist: /net/nfs/PAT/home/matias/data/blacklist/hypervariable_gene_blacklist.bed
    Gene_blacklist: /net/nfs/PAT/archive/Yongsoo/Resource/blacklist/hypervariable_gene_blacklist.bed



Mutect2:
    gnomad: /net/nfs/PAT/archive/Resource/dbSNP/2.0.2/gnomad.exomes.r2.0.2-AF_chr.vcf.gz
    pon: "null"
    interval: /net/nfs/PAT/archive/Resource/KAPA_New_Exome/KAPA_HyperExome_hg19_primary_targets.bed
    clustered: 50 
    af_min: 0.05
    reads_per_strand: 3
    min_reads: 4
    variants: /net/nfs/PAT/analysis/MPS-409/WES/tumor-only-snakemake/manifests/variants_for_contamination.vcf.gz
    interval: /net/nfs/PAT/archive/Resource/KAPA_New_Exome/KAPA_HyperExome_hg19_primary_targets.bed

Funcotator:
    #datasource: /net/nfs/PAT/home/tjitske/files/funcotator_db/funcotator_dataSources.v1.7.20200521s
    datasource: /net/nfs/PAT/archive/Resource/Funcotator/funcotator_dataSources.v1.7.20200521s
    hg_version: hg19    #alternative is hg38 
    file_format: VCF #alternative is MAF output file
    transcriptlist: manifests/transcriptlist.txt

vcf2maf:
    vep_fasta: /net/nfs/PAT/archive/Resource/fasta/hg19.chr.fa
    vep_path:  /net/beegfs/cfg/tgac/yokim/miniconda3/envs/WES/bin/
    vep_data: /net/beegfs/cfg/tgac/b.andradebar/vep/
