
path:
    fastq: '/home/m.mendeville/MPS-408/WES/fastq'
#    fastq: '/net/nfs/PAT/analysis/MPS-408/WES/fastq'
    trimmed: '/home/m.mendeville/PETAL/trimmed'
    qc: '/home/m.mendeville/PETAL/qc'
    bam: '/home/m.mendeville/PETAL/bam'
    log: '/home/m.mendeville/PETAL/log'
    covariance: '/home/m.mendeville/PETAL/CovMetrics'
    temp: '/home/m.mendeville/temp/'

platform:
    SRorPE: 'PE'
    prefix: ['_R1_001', '_R2_001']

cutadapt:
    adapter: ["AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC", #standard Illumena 
              "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"]

all:
    REF: /home/m.mendeville/data/ref/incl_chr/hg19.fa
    THREADS: 24
    Java_mem: -Xmx4g
    targets: KAPA_New_Exome/KAPA_HyperExome_hg19_primary_targets.bed
    bait_intervals: KAPA_New_Exome/KAPA_New_Exome_bait_intervals_HG19.txt
    target_intervals: KAPA_New_Exome/KAPA_New_Exome_target_intervals_HG19.txt
    #targets: manifest/MedExome_hg19_primary_coord.bed
    #dbsnp: "/net/nfs/PAT/home/tjitske/dbSNP/b151/All_20180423_Mutect2_AF.vcf.gz"  #dbSNP b151 excl chr
    dbsnp: /net/nfs/PAT/home/matias/dbSNP/b151/All_20180423.vcf.gz
    #snps: /net/nfs/PAT/home/tjitske/dbSNP/gnomAD/2.0.2/gnomad.exomes.r2.0.2-AF_chr.vcf.gz #gnomAD incl chr
    snps: /net/nfs/PAT/home/tjitske/dbSNP/gnomAD/2.0.2/gnomad.exomes.r2.0.2-AF.vcf.gz  #gnomAD excl chr
    #snps: /net/nfs/PAT/home/tjitske/dbSNP/b151/All_20180423_Mutect2_AF_chr.vcf.gz  #dbSNP b151 incl chr
    clinvar: /net/nfs/PAT/home/matias/dbSNP/b151/clinvar_20180701.vcf.gz
    #Cosmic: /net/nfs/PAT/home/matias/data/ref/cosmic/hg19_v84_2018/CosmicCodingMuts_BCNHLv2_v84_hg19.vcf
    Cosmic: /net/nfs/PAT/home/matias/data/ref/cosmic/hg19_v84_2018/CosmicCodingMuts_Custom_v84_hg19.vcf

trim:
    min_len: 20
