all:
    REF_CHR: /net/nfs/PAT/home/tjitske/files/ref/incl_chr/hg19.fa
    REF_NOCHR: /net/nfs/PAT/home/tjitske/files/ref/excl_chr/hg19_refgen_exclchr.fa
    THREADS: 4
    targets: manifest/BCNHLv2_primary_coord.bed
    bait_intervals: manifest/BCNHLv2_bait_intervals.txt
    target_intervals: manifest/BCNHLv2_target_intervals.txt

trim:
    min_len: 20
    SeqPurge: /net/nfs/PAT/home/tjitske/ngs-bits/bin/SeqPurge

abra:
    abra_prog: /net/nfs/PAT/home/tjitske/abra/abra-0.96-SNAPSHOT-jar-with-dependencies.jar

baseRecalibration:
    known_indels: /net/nfs/PAT/data/ref/gatk_bundle/2.8/hg19/Mills_and_1000G_gold_standard.indels.hg19.vcf
    known_snps: /net/nfs/PAT/data/ref/gatk_bundle/2.8/hg19/dbsnp_138.hg19.vcf
