channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.5.1
  - snakemake=4.3.0
  - graphviz=2.38.0
  - picard=2.15.0
  - samtools=1.3.1
  - bwa=0.7.12
  - fastqc=0.11.5
  - gatk4=4.0.1.2
  - sambamba=0.6.6
  - r-base
  - ensembl-vep=102.0
