channels:
  - conda-forge
  - bioconda
  - r
  - defaults
 dependencies:
  - bwa=0.7.12
  - graphviz=2.38.0
  - picard=2.15.0
  - python=3.5.1
  - samtools=1.3.1
  - snakemake=4.3.0
  - fastqc=0.11.5
